juegos = [
    {"Nombre":"Cuphead",
     "linkHowLTB":"https://howlongtobeat.com/game?id=21680",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/cuphead",
     "linkPlay":"https://store.playstation.com/en-au/product/EP8254-CUSA20469_00-CUPHEAD000000000",
     "linkHumbleB":"https://www.humblebundle.com/store/cuphead"},

     {"Nombre":"Borderlands 2",
     "linkHowLTB":"https://howlongtobeat.com/game?id=1274",
     "linkMetacritic":"https://www.metacritic.com/game/pc/borderlands-2",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP1001-CUSA13897_00-000000000000BLVR",
     "linkHumbleB":"https://www.humblebundle.com/store/borderlands-2"},

     {"Nombre":"Far Cry 4",
     "linkHowLTB":"https://howlongtobeat.com/game?id=19310",
     "linkMetacritic":"https://www.metacritic.com/game/pc/far-cry-4",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0001-CUSA00496_00-FC4GAMEPS4000001",
     "linkHumbleB":"https://www.humblebundle.com/store/far-cry-4"},

     {"Nombre":"Call of Duty: Modern Warfare 2",
     "linkHowLTB":"https://howlongtobeat.com/game?id=1477",
     "linkMetacritic":"https://www.metacritic.com/game/pc/call-of-duty-modern-warfare-2",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0002-CUSA09249_00-CODMW2RSTANDARD1",
     "linkHumbleB":"https://www.humblebundle.com/store/call-of-duty-modern-warfare-2?hmb_source=search_bar"},

     {"Nombre":"Final Fantasy XV",
     "linkHowLTB":"https://howlongtobeat.com/game?id=3537",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/final-fantasy-xv",#Cambiarlo
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0082-CUSA01633_00-FFXVROYALEDITION",
     "linkHumbleB":"https://www.humblebundle.com/store/final-fantasy-xv-windows-edition?hmb_source=search_bar"},

     {"Nombre":"Bioshock Infinite",
     "linkHowLTB":"https://howlongtobeat.com/game?id=1068",
     "linkMetacritic":"https://www.metacritic.com/game/pc/bioshock-infinite",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP1001-CUSA03980_00-BIOSHOCKCOMPLETE",
     "linkHumbleB":"https://www.humblebundle.com/store/bioshock-infinite?hmb_source=search_bar"},

     {"Nombre":"GTA V",
     "linkHowLTB":"https://howlongtobeat.com/game?id=4064",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/grand-theft-auto-v",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP1004-CUSA00419_00-GTAVDIGITALDOWNL",
     "linkHumbleB":"https://www.humblebundle.com/store/grand-theft-auto-v?hmb_source=search_bar"},

     {"Nombre":"Resident Evil 4",
     "linkHowLTB":"https://howlongtobeat.com/game?id=7720",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/resident-evil-4",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0102-CUSA04885_00-BH4HD00000000001",
     "linkHumbleB":"https://www.humblebundle.com/store/resident-evil-4?hmb_source=search_bar"},

     {"Nombre":"Bioshock",
     "linkHowLTB":"https://howlongtobeat.com/game?id=1065",
     "linkMetacritic":"https://www.metacritic.com/game/pc/bioshock",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP1001-CUSA13049_00-BIO1REMASTERED00",
     "linkHumbleB":"https://www.humblebundle.com/store/bioshock?hmb_source=search_bar"},

     {"Nombre":"God of War III",
     "linkHowLTB":"https://howlongtobeat.com/game?id=3978",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/god-of-war-iii-remastered",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP9000-CUSA01623_00-0000GODOFWAR3PS4",
     "linkHumbleB":"https://www.humblebundle.com/store/fallout-new-vegas-ultimate-edition"},#/// Cambiar

     {"Nombre":"Skyrim V",
     "linkHowLTB":"https://howlongtobeat.com/game?id=9859",
     "linkMetacritic":"https://www.metacritic.com/game/pc/the-elder-scrolls-v-skyrim",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP1003-CUSA05333_00-SKYRIMHDFULLGAME",
     "linkHumbleB":"https://www.humblebundle.com/store/the-elder-scrolls-v-skyrim-legendary-edition"},

     {"Nombre":"Doom (2016)",
     "linkHowLTB":"https://howlongtobeat.com/game?id=2708",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/doom",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP1003-CUSA02085_00-DOOMNORTHAMERICA",
     "linkHumbleB":"https://www.humblebundle.com/store/doom?hmb_source=search_bar"},

     {"Nombre":"Grand Theft Auto: San Andreas",
     "linkHowLTB":"https://howlongtobeat.com/game?id=4073",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-2/grand-theft-auto-san-andreas",
     "linkPlay":"https://store.playstation.com/en-is/product/EP1004-CUSA03541_00-SLES525410000001",
     "linkHumbleB":"https://www.humblebundle.com/store/grand-theft-auto-san-andreas?hmb_source=search_bar"},

     {"Nombre":"The Witcher 3: Wild Hunt",
     "linkHowLTB":"https://howlongtobeat.com/game?id=10270",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/the-witcher-3-wild-hunt",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP4497-CUSA00527_00-0000000000000002",
     "linkHumbleB":"https://www.humblebundle.com/store/the-witcher-3-wild-hunt?hmb_source=search_bar"},

     {"Nombre":"Red Dead Redemption 2",
     "linkHowLTB":"https://howlongtobeat.com/game?id=27100",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/red-dead-redemption-2",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP1004-CUSA03041_00-REDEMPTION000002",
     "linkHumbleB":"https://www.humblebundle.com/store/red-dead-redemption-2-ultimate-edition?hmb_source=search_bar"},

     {"Nombre":"Metal Gear Solid V: The Phantom Pain",
     "linkHowLTB":"https://howlongtobeat.com/game?id=5918",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/metal-gear-solid-v-the-phantom-pain",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0101-CUSA01140_00-MAINGAME00000000",
     "linkHumbleB":"https://www.humblebundle.com/store/metal-gear-solid-v-the-phantom-pain?hmb_source=search_bar"},

     {"Nombre":"Bloodborne",
     "linkHowLTB":"https://howlongtobeat.com/game?id=21262",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/bloodborne",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP9000-CUSA00900_00-BLOODBORNE000000",
     "linkHumbleB":"https://www.humblebundle.com/store/metal-gear-solid-v-the-phantom-pain?hmb_source=search_bar"},#/// Cambiar

     {"Nombre":"Dark Souls III",
     "linkHowLTB":"https://howlongtobeat.com/game?id=26803",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/dark-souls-iii",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0700-CUSA03388_00-DARKSOULS3000000",
     "linkHumbleB":"https://www.humblebundle.com/store/dark-souls-iii?hmb_source=search_bar"},

     {"Nombre":"Resident Evil 6",
     "linkHowLTB":"https://howlongtobeat.com/game?id=7725",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/resident-evil-6",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0102-CUSA03856_00-BH6HDPS400000000",
     "linkHumbleB":"https://www.humblebundle.com/store/resident-evil-6"},

     {"Nombre":"Resident Evil 7",
     "linkHowLTB":"https://howlongtobeat.com/game?id=38051",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/resident-evil-7-biohazard",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0102-CUSA03962_00-BH70000000000001",
     "linkHumbleB":"https://www.humblebundle.com/store/resident-evil-7-biohazard?hmb_source=search_bar"},

     {"Nombre":"Nier: Automata",
     "linkHowLTB":"https://howlongtobeat.com/game?id=38029",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/nier-automata",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0082-CUSA04551_00-NIERDLCPACK00000",
     "linkHumbleB":"https://www.humblebundle.com/store/nier-automata-game-of-the-yorha-edition?hmb_source=search_bar"},

     {"Nombre":"Dragon's Dogma: Dark Arisen",
     "linkHowLTB":"https://howlongtobeat.com/game?id=2846",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/dragons-dogma-dark-arisen",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0102-CUSA07385_00-DDDAFULLGAME0000",
     "linkHumbleB":"https://www.humblebundle.com/store/dragons-dogma-dark-arisen?hmb_source=search_bar"},

     {"Nombre":"RESIDENT EVIL HD REMASTER",
     "linkHowLTB":"https://howlongtobeat.com/game?id=22906",
     "linkMetacritic":"https://www.metacritic.com/game/pc/resident-evil-hd-remaster",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0102-CUSA01068_00-BHRHDPS400000001",
     "linkHumbleB":"https://www.humblebundle.com/store/resident-evil-hd-remaster?hmb_source=search_bar"},

     {"Nombre":"Fallout 4",
     "linkHowLTB":"https://howlongtobeat.com/game?id=26729",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/fallout-4",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP1003-CUSA03448_00-FALLOUT4FULLGAME",
     "linkHumbleB":"https://www.humblebundle.com/store/fallout-4?hmb_source=search_bar"},

     {"Nombre":"World War Z",
     "linkHowLTB":"https://howlongtobeat.com/game?id=64828",
     "linkMetacritic":"https://www.metacritic.com/game/pc/world-war-z",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP2746-CUSA14046_00-WWZTHEGAME201800",
     "linkHumbleB":"https://www.humblebundle.com/store/world-war-z-goty-edition-upgrade?hmb_source=search_bar"},

     {"Nombre":"Mortal Kombat X",
     "linkHowLTB":"https://howlongtobeat.com/game?id=38300",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/mortal-kombat-x",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP1018-CUSA00967_00-MORTALKOMBATX000",
     "linkHumbleB":"https://www.humblebundle.com/store/mortal-kombat-x?hmb_source=search_bar"},

     {"Nombre":"Assassing's Creed IV: Black Flag",
     "linkHowLTB":"https://howlongtobeat.com/game?id=12707",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/assassins-creed-iv-black-flag",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0001-CUSA00010_00-AC4GAMEPS4000001",
     "linkHumbleB":"https://www.humblebundle.com/store/assassins-creed-iv-black-flag?hmb_source=search_bar"},

     {"Nombre":"Watch Dogs: Legion",
     "linkHowLTB":"https://howlongtobeat.com/game?id=68237",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/watch-dogs-legion",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0001-CUSA13115_00-WDLSTND000000000",
     "linkHumbleB":"https://www.humblebundle.com/store/watch-dogs?hmb_source=search_bar"},

     {"Nombre":"WWE 2K20",
     "linkHowLTB":"https://howlongtobeat.com/game?id=71480",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/wwe-2k20",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP1001-CUSA15666_00-WWE2K20DELUXE000",
     "linkHumbleB":"https://www.humblebundle.com/store/wwe-2k20?hmb_source=search_bar"},

     {"Nombre":"Final Fantasy VII",
     "linkHowLTB":"https://howlongtobeat.com/game?id=3521",
     "linkMetacritic":"https://www.metacritic.com/game/playstation-4/final-fantasy-vii-remake",
     "linkPlay":"https://store.playstation.com/es-cr/product/UP0082-CUSA01875_00-FINALFANTASY7ZZZ",
     "linkHumbleB":"https://www.humblebundle.com/store/final-fantasy-vii?hmb_source=search_bar"}
]